apiVersion: v1
data:
  apiDomainName: api-gke.openindoor.io
  appDomainName: app-gke.openindoor.io
  certificateAuthority: https://acme-v02.api.letsencrypt.org/directory
  certificateAuthorityStaging: https://acme-staging-v02.api.letsencrypt.org/directory
  storageClassName: standard
kind: ConfigMap
metadata:
  name: openindoor-cm
