version: "3.6"
services:


  map-app:
    build:
      context: map-app
    image: openindoor/map-app
    volumes:
    - ./map-app/Caddyfile:/tmp/Caddyfile
    - ./map-app/map-app.sh:/usr/bin/map-app.sh
    - ./map-app/www/:/map-app/www/
    environment:
      API_DOMAIN_NAME: ${API_DOMAIN_NAME}
      APP_DOMAIN_NAME: ${APP_DOMAIN_NAME}
      APP_URL: "http://${APP_DOMAIN_NAME}:8000"

  mapbox-gl-openindoor:
    build:
      context: mapbox-gl-openindoor
    image: openindoor/mapbox-gl-openindoor
    volumes:
    - ./mapbox-gl-openindoor/Caddyfile:/etc/caddy/Caddyfile
    - ./mapbox-gl-openindoor/mapbox-gl-openindoor.sh:/usr/bin/mapbox-gl-openindoor.sh

  sprite-app:
    build:
      context: sprite-app
    image: openindoor/sprite-app
    volumes:
    - ./sprite-app/Caddyfile:/etc/caddy/Caddyfile
    - ./sprite-app/sprite-app.sh:/usr/bin/sprite-app.sh

  style-app:
    build:
      context: style-app
    image: openindoor/style-app
    volumes:
    - ./style-app/Caddyfile:/etc/caddy/Caddyfile
    - ./style-app/style-app.sh:/usr/bin/style-app.sh
    environment:
      APP_URL: "http://${APP_DOMAIN_NAME}:8000"
      API_URL: "http://${API_DOMAIN_NAME}"

  front-app:
    build:
      context: front-app
    image: openindoor/front-app
    volumes:
    - ./front-app/Caddyfile:/tmp/Caddyfile_
    - ./front-app/front-app.sh:/usr/bin/front-app.sh
    environment:
      APP_DOMAIN_NAME: ${APP_DOMAIN_NAME}
      APP_SERVER: ":80"
      APP_URL: http://${APP_DOMAIN_NAME}:8000
      CADDY_TLS: " "
    ports:
    - 8000:80

  geojson-api:
    build:
      context: geojson-api
    image: openindoor/geojson-api
    volumes:
    - ./geojson-api/Caddyfile:/etc/caddy/Caddyfile_
    # - ./geojson-api/places-api.sh:/geojson/geojson-api.sh
    - ./geojson-api/geojson.py:/geojson/geojson
    environment:
      API_DOMAIN_NAME: ${API_DOMAIN_NAME}

  mbtiles-api:
    build:
      context: mbtiles-api
    image: openindoor/mbtiles-api
    volumes:
    - ./mbtiles-api/Caddyfile:/tmp/Caddyfile
    - ./mbtiles-api/mbtiles-api.sh:/mbtiles/mbtiles-api.sh
    - ./mbtiles-api/mbtiles.sh:/mbtiles/mbtiles
    environment:
      API_DOMAIN_NAME: ${API_DOMAIN_NAME}

  osm-api:
    build:
      context: osm-api
    image: openindoor/osm-api
    volumes:
    - ./osm-api/Caddyfile:/tmp/Caddyfile
    - ./osm-api/action.py:/usr/bin/action
    - ./osm-api/osm-api.sh:/osm/osm-api.sh
    environment:
      API_DOMAIN_NAME: ${API_DOMAIN_NAME}
      API_URL: http://${API_DOMAIN_NAME}

  places-api:
    build:
      context: places-api
    image: openindoor/places-api
    volumes:
    - ./places-api/Caddyfile:/etc/caddy/Caddyfile_
    - ./places-api/places-api.sh:/places/places-api.sh
    - ./places-api/places.py:/places/places
    environment:
      API_DOMAIN_NAME: ${API_DOMAIN_NAME}
      APP_URL: http://${APP_DOMAIN_NAME}
    
  front-api:
    build:
      context: front-api
    image: openindoor/front-api
    volumes:
    - ./front-api/Caddyfile:/tmp/Caddyfile
    - ./front-api/front-api.sh:/usr/bin/front-api.sh
    - ./front-api/index.html:/tmp/index_template.html
    environment:
      # CERTIFICATE_AUTHORITY: https://acme-staging-v02.api.letsencrypt.org/directory
      API_DOMAIN_NAME: ${API_DOMAIN_NAME}
      API_SERVER: ${API_DOMAIN_NAME}:80
      API_URL: http://${API_DOMAIN_NAME}
      CADDY_TLS: " "
    ports:
    - 80:80