version: "3.6"
services:

  overpassCache:
    image: varnish:6.2
    tmpfs: /var/lib/varnish:exec
    volumes:
    - ./overpassCache/default.vcl:/etc/varnish/default.vcl:ro
    - ./overpassCache/run.sh:/run.sh
    - ./overpassCache/docker-varnish-entrypoint:/usr/local/bin/docker-varnish-entrypoint

  tileCache:
    image: varnish:6.2
    tmpfs: /var/lib/varnish:exec
    volumes:
    - ./tileCache/default.vcl:/etc/varnish/default.vcl:ro
    - ./tileCache/run.sh:/run.sh
    - ./tileCache/docker-varnish-entrypoint:/usr/local/bin/docker-varnish-entrypoint

  fonts:
    build:
      context: ./fonts
    volumes:
    - ./fonts/Caddyfile:/etc/Caddyfile

  openindoor4:
    build:
      context: .
    # image: openindoor4/openindoor
    environment:
      - WEB_SITE=${WEB_SITE}
      - CADDYFILE=Caddyfile_${DOMAIN_NAME}
      - OVERPASS_API=${OVERPASS_API}
    volumes:
    - ./Caddyfiles:/etc/caddy/Caddyfiles
    - ./index_template.html:/openindoor/index_template.html
    - ./openmaptiles.html:/openindoor/openmaptiles.html
    - ./favicon.ico:/openindoor/favicon.ico
    - ./layer/indoorLayers.json:/openindoor/layer/indoorLayers.json

    ports:
    - 80:80
    - 443:443
