version: "3.6"
services:


  # map-app:
  #   build:
  #     context: map-app
  #   image: openindoor/map-app
  #   volumes:
  #   - ./map-app/Caddyfile:/tmp/Caddyfile
  #   - ./map-app/map-app.sh:/usr/bin/map-app.sh
  #   - ./map-app/www/:/map-app/www/
  #   #- ./map-app/www/local.html:/map-app/www/index.html
  #   environment:
  #     API_DOMAIN_NAME: ${API_DOMAIN_NAME}
  #     APP_DOMAIN_NAME: ${APP_DOMAIN_NAME}
  #     APP_URL: "http://${APP_DOMAIN_NAME}:8000"

  sprite-app:
    build:
      context: sprite-app
    image: openindoor/sprite-app
    volumes:
    - ./sprite-app/Caddyfile:/etc/caddy/Caddyfile
    - ./sprite-app/sprite-app.sh:/usr/bin/sprite-app.sh

  style-app:
    build:
      context: style-app
    image: openindoor/style-app
    volumes:
    - ./style-app/Caddyfile:/etc/caddy/Caddyfile
    - ./style-app/style-app.sh:/usr/bin/style-app.sh
    - ./style-app/processStyle.py:/usr/bin/processStyle
    - ./style-app/actions.sh:/usr/bin/actions.sh
    environment:
      APP_URL: "http://${APP_DOMAIN_NAME}:8000"
      API_URL: "http://${API_DOMAIN_NAME}"
      BUILDING_GEOJSON: "http://${API_DOMAIN_NAME}/geojson/data/france/FranceParisGareDeLEst"
      INDOOR_GEOJSON: "http://${API_DOMAIN_NAME}/geojson/data/france/FranceParisGareDeLEst"
      SHAPE_GEOJSON: "http://${API_DOMAIN_NAME}/geojson/data/france/FranceParisGareDeLEst"

  # rastertiles-app:
  #   build:
  #     context: rastertiles-app
  #   image: openindoor/rastertiles-app

  front-app:
    build:
      context: front-app
    image: openindoor/front-app
    volumes:
    - ./front-app/Caddyfile:/tmp/Caddyfile_
    - ./front-app/front-app.sh:/usr/bin/front-app.sh
    environment:
      APP_DOMAIN_NAME: ${APP_DOMAIN_NAME}
      APP_SERVER: ":80"
      APP_URL: http://${APP_DOMAIN_NAME}:8000
      CADDY_TLS: ""
    ports:
    - 8000:80

  geojson-api:
    build:
      context: geojson-api
    image: openindoor/geojson-api
    volumes:
    - ./geojson-api/Caddyfile:/etc/caddy/Caddyfile_
    # - ./geojson-api/places-api.sh:/geojson/geojson-api.sh
    - ./geojson-api/geojson.py:/geojson/geojson
    environment:
      API_DOMAIN_NAME: ${API_DOMAIN_NAME}

  mbtiles-api:
    build:
      context: mbtiles-api
    image: openindoor/mbtiles-api
    volumes:
    - ./mbtiles-api/Caddyfile:/tmp/Caddyfile
    - ./mbtiles-api/mbtiles-api.sh:/mbtiles/mbtiles-api.sh
    - ./mbtiles-api/mbtiles.sh:/mbtiles/mbtiles
    - ./mbtiles-api/actions.sh:/usr/bin/actions.sh
    environment:
      API_DOMAIN_NAME: ${API_DOMAIN_NAME}
      API_URL: http://${API_DOMAIN_NAME}

  mbtiles-country-api:
    build:
      context: mbtiles-country-api
    image: openindoor/mbtiles-country-api
    volumes:
    - ./mbtiles-country-api/Caddyfile:/tmp/Caddyfile
    - ./mbtiles-country-api/mbtiles-country-api.sh:/mbtiles-country/mbtiles-api.sh
    - ./mbtiles-country-api/mbtiles-country.sh:/mbtiles-country/mbtiles-country
    - ./mbtiles-country-api/actions.sh:/usr/bin/actions.sh
    environment:
      API_DOMAIN_NAME: ${API_DOMAIN_NAME}
      API_URL: http://${API_DOMAIN_NAME}

  osm-api:
    build:
      context: osm-api
    image: openindoor/osm-api
    volumes:
    - ./osm-api/Caddyfile:/tmp/Caddyfile
    - ./osm-api/action.py:/usr/bin/action
    - ./osm-api/osm-api.sh:/osm/osm-api.sh
    environment:
      API_DOMAIN_NAME: ${API_DOMAIN_NAME}
      API_URL: http://${API_DOMAIN_NAME}

  places-api:
    build:
      context: places-api
    image: openindoor/places-api
    volumes:
    - ./places-api/Caddyfile:/etc/caddy/Caddyfile_
    - ./places-api/places-api.sh:/places/places-api.sh
    - ./places-api/places.py:/places/places
    environment:
      API_DOMAIN_NAME: ${API_DOMAIN_NAME}
      APP_URL: http://${APP_DOMAIN_NAME}
    
  front-api:
    build:
      context: front-api
    image: openindoor/front-api
    volumes:
    - ./front-api/Caddyfile:/tmp/Caddyfile
    - ./front-api/front-api.sh:/usr/bin/front-api.sh
    - ./front-api/index.html:/tmp/index_template.html
    environment:
      # CERTIFICATE_AUTHORITY: https://acme-staging-v02.api.letsencrypt.org/directory
      API_DOMAIN_NAME: ${API_DOMAIN_NAME}
      API_SERVER: ${API_DOMAIN_NAME}:80
      API_URL: http://${API_DOMAIN_NAME}
      CADDY_TLS: ""
    ports:
    - 80:80

  tileserver-api:
    build:
      context: tileserver-api
    image: openindoor/tileserver-api
    volumes:
    - ./tileserver-api/Caddyfile:/tmp/Caddyfile
    - ./tileserver-api/front-api.sh:/usr/bin/front-api.sh
    - ./tileserver-api/index.html:/tmp/index_template.html
    environment:
      API_DOMAIN_NAME: ${API_DOMAIN_NAME}

  openindoor-app:
    build:
      context: openindoor-app
    image: openindoor/openindoor-app
    command: yarn serve --port 80
    volumes:
    - ./openindoor-app/src:/openindoor-app/src
    environment:
      API_DOMAIN_NAME: ${API_DOMAIN_NAME}
      API_URL: http://${API_DOMAIN_NAME}
    ports:
    - 8080:80

  openindoor-db:
    image: postgis/postgis:12-3.1
    environment:
      POSTGRES_DB: openindoor-db
      POSTGRES_USER: openindoor-db-admin
      POSTGRES_PASSWORD: admin123
      API_URL: http://api-sandbox.openindoor.io
      APP_URL: http://app-sandbox.openindoor.io      
    volumes:
    - ./test/data:/data
    # - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
    - 5432:5432

  openindoor-rex:
    build:
      context: openindoor-rex
    image: openindoor/openindoor-rex
    command: t_rex serve --config config.toml
    volumes:
    - ./openindoor-rex/test/data:/data
    - ./openindoor-rex/config.toml:/openindoor-rex/config.toml
    environment:      
      API_URL: http://api-sandbox.openindoor.io
      APP_URL: http://app-sandbox.openindoor.io
    ports:
    - 6767:6767