apiVersion: v1
kind: Service
metadata:
  name: mapbox-gl-js
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: mapbox-gl-js
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: mapbox-gl-js
  name: mapbox-gl-js
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mapbox-gl-js
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: mapbox-gl-js
    spec:
      containers:
      - env:
        - name: APP_DOMAIN_NAME
          valueFrom:
            configMapKeyRef:
              name: openindoor-cm
              key: appDomainName
        image: openindoor/mapbox-gl-js:0.0.0
        name: mapbox-gl-js
        ports:
        - containerPort: 80
