apiVersion: v1
kind: Service
metadata:
  name: openindoor-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: openindoor-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: openindoor-app
  name: openindoor-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: openindoor-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: openindoor-app
    spec:
      containers:
      - env:
        - name: API_DOMAIN_NAME
          valueFrom:
            configMapKeyRef:
              name: openindoor-cm
              key: apiDomainName
        - name: APP_DOMAIN_NAME
          valueFrom:
            configMapKeyRef:
              name: openindoor-cm
              key: appDomainName
        - name: ANALYTICS
          valueFrom:
            configMapKeyRef:
              name: openindoor-cm
              key: analytics
        - name: GOOGLE_ANALYTICS_ID
          valueFrom:
            configMapKeyRef:
              name: openindoor-cm
              key: googleAnalyticsId
        image: openindoor/openindoor-app:0.0.0
        name: openindoor-app
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "800Mi"
            cpu: "0.5"
          requests:
            memory: "400Mi"
            cpu: "0.25"
