apiVersion: v1
kind: Service
metadata:
  name: geojson
  labels:
    app: geojson
spec:
  # type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: geojson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geojson
  labels:
    app: geojson
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geojson
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: geojson
    spec:
      containers:
      - name: geojson
        image: openindoor/geojson:1.0.8
