#!/bin/sh
set -e

varnishd -f /etc/varnish/default.vcl -a http=:80,HTTP -s malloc,$VARNISH_SIZE

/usr/bin/varnishncsa \
  -b -c \
  -F '%{Host}i %h %l %u %t \"%r\" %s %b \"%{Referer}i\" \"%{User-agent}i\" \"%{Varnish:hitmiss}x\"'
# # this will check if the first argument is a flag
# # but only works if all arguments require a hyphenated flag
# # -v; -SL; -f arg; etc will work, but not arg1 arg2
# if [ "$#" -eq 0 ] || [ "${1#-}" != "$1" ]; then
#     set -- varnishd -F -f /etc/varnish/default.vcl -a http=:80,HTTP -s malloc,$VARNISH_SIZE "$@"
# fi

# exec "$@"





# #!/bin/bash

# mkdir -p /var/lib/varnish/`hostname` && chown nobody /var/lib/varnish/`hostname`
# /usr/sbin/varnishd -s malloc,128M -a :80 -f /etc/varnish/default.vcl

# /usr/bin/varnishncsa \
#   -q 'ReqURL ne "<url_which_should_be_not_logged>"' \
#   -F '%{Host}i %h %l %u %t \"%r\" %s %b \"%{Referer}i\" \"%{User-agent}i\" \"%{Varnish:hitmiss}x\"'
