apiVersion: v1
data:
  apiDomainName: api-sandbox.openindoor.io
  appDomainName: app-sandbox.openindoor.io
  googleAnalyticsId: G-D2YH8YW0P1
  analytics: |-
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-D2YH8YW0P1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-D2YH8YW0P1');
    </script>
  certificateAuthority: https://acme-v02.api.letsencrypt.org/directory
  certificateAuthorityStaging: https://acme-staging-v02.api.letsencrypt.org/directory
  storageClassName: standard
kind: ConfigMap
metadata:
  name: openindoor-cm
