apiVersion: v1
data:
  domainName: api-ovh.openindoor.io
  # domainNames: "api.openindoor.io api-ovh.openindoor.io"
  domainNames: "api-ovh.openindoor.io"
  # certificateAuthority: https://acme-staging-v02.api.letsencrypt.org/directory
  certificateAuthority: https://acme-v02.api.letsencrypt.org/directory
kind: ConfigMap
metadata:
  name: openindoor-cm
