export BUILDING_MIN_ZOOM=15
export BUILDING_MAX_ZOOM=18
export BUILDING_TALL_ZOOM=17
export BUILDING_FLAT_ZOOM=18
export SHAPE_MIN_ZOOM=16
export SHAPE_MAX_ZOOM=18
export INDOOR_MIN_ZOOM=18
export INDOOR_ROOM_COLOR="#888888"